### PR TITLE
Bump hast-util-raw to the latest

### PR DESCRIPTION
**Pull request by revelt**
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [x] If applicable, I’ve added docs and tests

### Description of changes

- bump `hast-util-raw` to latest; possibly partially solves https://github.com/inikulin/parse5/issues/861 (also dependent on https://github.com/rehypejs/rehype/pull/129)

### CODE REVIEW

**Comment by wooorm** [comment]
I think it’s better to switch to `Raw` from `mdast-util-to-hast`.
That’s the place that really defines `Raw` nodes.
`hast-util-raw` re-exports that now: https://github.com/syntax-tree/hast-util-raw/commit/b83ec5fb50d9f673454754d2c088569f64b4e529.

**Comment by revelt** [comment]
> Am I correct in assuming you are working with Remix?

My monorepo just houses npm packages, they're not related directly to `remix`, but the main purpose of `remark-conventional-commit-changelog-timeline` was indeed for my Remix [website](https://codsen.com/os/string-strip-html/changelog), to transform the Conventional Commit changelogs into something which can be styled nicer, in a timeline.

**Comment by revelt** [comment]
closing, will raise a new PR tonight late

**Comment by wooorm** [comment]
This will probably help: https://twitter.com/bradgarropy/status/1632589349744254976.

**Comment by revelt** [comment]
yeah, we need to update all unist ecosystem packages to ensure there's no parse5 v6 anywhere in the dependency trees

**Pull request closed without merging**
